### ISSUE TITLE
After clearCache() a Resource might still be cached by the browser

### ISSUE THREAD

**Issue by aradsziw** [badgateway/ketting#185]
Hi,
I just ran into a case, where a get() after clearCache() still returned a stale copy of a resource that came from a browser's cache instead.

I solved the issue by using:  
```
someResource.clearCache();
someResource.addNextRefreshHeader("cache-control", "no-cache");
const repr = someResource.get();
```
I know clearCache says it resets the internal Cache. But there are cases where that may not be enough to ensure a fresh copy.
Maybe the documentation of clearCache() could be expanded to mention the addNextRefreshHeader() function for the case that Ketting is running in a browser. 

Also could you add the following to the API docs in the wiki?
 ```
  /**
   * When a HTTP header gets added here, it will automatically get sent along
   * to the next call to refresh().
   *
   * This means that the next time a GET request is done, these headers will be
   * added. This list gets cleared after the GET request.
   */
  addNextRefreshHeader(name: string, value: string): void;
```

**Comment by evert** [comment]
I've been trying to think about what to do exactly with this. The complication is the difference between server-side usage and client-side.

On the client-side it might be desired to not do any ketting-level caching at all, or at least give that option. Then you can just fully rely on browser cache.

I also thought it might be good to introduce browser-like caching support to ketting on node.js, so respecting `Cache-Control`, `Expires`, `ETag`, etc..

So I'm keeping this open for now, i think this just needs a bit more thought and a more holistic approach. At the very least we can add something to the `.refresh()` header, which BTW is probably what you should be using here instead of `clearCache`

**Comment by aradsziw** [comment]
Thank you for replying.

I mostly opened the issue, so others might have a reference in case they encounter similar problems. For me, it was a bit of a 'gotcha' moment, since there are two levels of caching involved.

So, if you're running Ketting in a browser setting, and you want to ensure you don't get a cached version of your resource, you have to both clear the Ketting resource's cache **and** set a cache-control header for the browser.

I agree, that it would be nice, if caching behaviour could be controlled in a uniform way, no matter the setting.

**Comment by webD97** [comment]
I'm using Ketting on the client side and would prefer if it delegated caching to the browser.
