### ISSUE TITLE
StateCache and embedded states

### ISSUE THREAD

**Issue by reda-alaoui** [badgateway/ketting#297]
I am using HAL with Ketting 6.0.4 in a browser environment.

Let's consider a user resource.
I have an endpoint `/users` that list all users.
`/users` returns this kind of representation:
```json
{
  "_embedded": {
    "content": [{
      "name": "John Doe",
      "_links": {
        "self": {
          "href": "/users/1"
        }
      }
    }]
  }
}
```

Here is the code that consumes the endpoint:
```typescript
await this.ketting
      .follow('users')
      .followAll('content');
```

By default, since the `EternalCache` is used, this triggers a single http request on `/users`.

`EternalCache` is not what we want (partly because Ketting is not the only http client we use and we want to rely on browser native http cache), so we thought we could use `NeverCache`. But with `NeverCache`, the above code triggers 2 http requests, first on `/users` and the second on `/users/1`.

Ideally we would need 2 cache policies:
- one for embedded values (we would set it to `Eternal` or `Short` for our use case)
- one for the rest (we would set it to `Never` for our use case)

I don't know yet if we can do that with the current `StateCache` abstraction. 

But I think segmenting the caching policy around the above 2 categories would make sense to many Ketting users.

**Comment by reda-alaoui** [comment]
So I ended with this non perfect `StateCache` implementation:

```typescript
class EmbeddedOnlyShortCache implements StateCache {

  private readonly delegate: StateCache;

  constructor(cacheTimeoutInMs: number) {
    this.delegate = new ShortCache(cacheTimeoutInMs);
  }

  clear(): void {
    this.delegate.clear();
  }

  delete(uri: string): void {
    this.delegate.delete(uri);
  }

  get(uri: string): State | null {
    return this.delegate.get(uri);
  }

  has(uri: string): boolean {
    return this.delegate.has(uri);
  }

  store(state: State): void {
    state
      .getEmbedded()
      .forEach(embeddedState => this.delegate.store(embeddedState));
  }
}
```

It is not perfect because the segmentation between embedded and non embedded can only happen in the `store` method. When called via `get` method, the cache has no way to know if the element is retrieved in the context of an embedding resource (followAll) or not.

Maybe, in addition to the global cache, each resource should have its own cache instance dedicated to its embedded resources.

**Comment by evert** [comment]
Hey ! 

The usecase you are describing sounds like the exact reason for the third cache strategy : ShortCache.

There's a few other cases where this will work better than just dividing by embedded/non-embedded.

Btw EternalCache sounds so much better than ForeverCache

**Comment by reda-alaoui** [comment]
Hi @evert :) ,

We also tried with `ShortCache`, but it doesn't not solve our issue.

To be more concrete, what we want is:
- `NeverCache` behaviour for `/users` and `/users/1`
- `ShortCache` behaviour for `/users/1` in the context of `/users`

**Comment by evert** [comment]
Could you help me understand under what circumstances ShortCache is bad for you? The pattern is similar to what you would get if you were to use HTTP/2 Push for instance, just a very temporary cache with responses ready to go for the next few seconds.

One issue with dividing things up per type of response (embedded, non-embedded) is that it's not the only case where you might see extra requests where you kinda don't want to, for example... with NeverCache on `/users`, this results in 3 GET requests:

    const foo = await resource.follow('rel1');
    const bar = await resource.follow('rel2');
    const state = await resource.get();

Also, the cache will get updated when you do a `.put()` or if the server responds correctly to a request with `Prefer: return=representation`. 

So I don't think I'd want `EmbeddedOnlyShortCache` as a built-in feature, but I am open to ways where it's easier/better for you to implement it. 

> Maybe, in addition to the global cache, each resource should have its own cache instance dedicated to its embedded states.

Storing these is not cheap :/ I'm not sure if I want a second copy in memory for every embedded item. I also feel it goes a bit against the general Ketting concept if we're treating embedded different as regular resources.

We could add a third parameter to .store() that could be an enum like `'embedded' | 'get-response' | 'put-request` | 'etc..` with all the ways that something can enter the cache.

But, I'd still recommend you try to work with the cache rather than against. Without, a bunch of features will just not work or work as well. If you'd ever want to use `react-ketting` for example you're basically out of luck without a cache =)

**Comment by reda-alaoui** [comment]
> Could you help me understand under what circumstances ShortCache is bad for you?

Of course, here is a detailed example. The public root path of our api exposes available root links (i.e. index summary) like that:
```
GET /

{
  "_links": {
    "users": {"href": "/users"},
    "current-user": {"href": "/current-user"}
  }
}
```

Relation `current-user` is conditionally exposed. If the http request is authenticated, `current-user` will be present in the index summary. If the http request is not authenticated, `current-user` will be absent.

Our authentication process uses Ketting. Since the auth cookie is HttpOnly, the only way to know the browser is authenticated is by asking the server. 
The process works roughly like that:
1- It fetches the index summary using Ketting
2- If `current-user` relation is absent from the index summary it concludes that the browser is not authenticated
3- If step 2 fails, it performs authentication
4- It fetches the index summary again for `current-user`

Sometimes, the process is so fast, that it executes in less than one second, leading it to fetch the stale index summary representation (missing `current-user`) in step 4.

> The pattern is similar to what you would get if you were to use HTTP/2 Push for instance, just a very temporary cache with responses ready to go for the next few seconds.

Yes you are right. I didn't think of it this way.
IMO, ideally, the cache policy should be controlled by the server and in this case I would use HTTP/2 Push in the context of resource embedding.

So afterthought, `EmbeddedOnlyShortCache` above is the best client side cache I can think of.
We can close this if it is ok for you.

Thank you for your help :)

**Comment by reda-alaoui** [comment]
But out of curiosity, how would you manage the authentication process example with a `ForeverCache` ?

**Comment by evert** [comment]
Hi @reda-alaoui ,

I think I will close this until  I have a better way to resolve this in a more universal way... but a few more thoughts:

Ketting needs to eventually need to go to a server-controlled cache via headers. It's a total pain because we don't have programmatic access to the _actual _browser cache, (Which I would prefer to use anyway), so I'm not sure entirely how this will work. A server telling Ketting to never cache via a header is imho the ideal solution here. 

The way our applications effectively work is that we aggressively cache absolutely everything, but have several ways to communicate from server to client that certain things should be marked as stale and expire.

Some examples:

* If we do a `DELETE` request somewhere, the server will emit a `Link: </collection>; rel="invalidates"` header to tell Ketting to automatically remove related resources from a cache.
* For  real-time multi-user applications, we actually have websockets that send 'stale' events per-resource to every connected user. Javascript frontends respond to 'stale' events by doing an instant refresh.

Because my head is kind of working like this, I would ask.. instead of *never* storing the home document in cache, do you have a way to just expire it at the exact time you need it?

1. If you're fetching the body with `.get()`, you could for _just_ the home case, always use `.refresh()` instead.
2. If you control the authentication server, the server can tell the client to expire the home document (with an 'invalidates' link header).
3. If authentication is handled with javascript and is (for example) OAuth2, you could run: `client.gp('/').refresh()` after you get redirected back successfully from the auth process.
