### ISSUE TITLE
Unable to follow links from POST-only resources

### ISSUE THREAD

**Issue by sazzer** [badgateway/ketting#325]
I've got a situation where I've got a resource that doesn't really exist, but that I still want to follow links from.

I'm building a login/register flow, where the client will:
* Perform a `POST` to `/authentication` with the username.
* Receive a response containing one of two links - identified as either `rels/authentication/authenticate` or `rels/authentication/register` - depending on whether the username exists.
* Perform a `POST` to the link that was returned with the appropriate details.

So what I've done is:
* Create a new Ketting Client.)
* Perform a `GET` to `/` to get the home document
* Follow the link with the rel `rels/authentication` and perform a `POST` to this with the username - this is `/authentication`
* Follow the link with the rel `rels/authentication/authenticate` and perform a `POST to this with the username and password.

The result is that Ketting is then trying to do a `GET` to `/authentication`, which returns an error because the server can't handle that, and then it errors out.

The code is effectively like this: (Restructured a little bit for brevity)
```
        const startAuthResource = await apiRoot.follow("rels/authentication");
        const response = await startAuthResource.post({ data: { username } });
        const authResource = await startAuthResource.follow("rels/authentication/authenticate"); // <-- Problem occurs here
```

**Comment by evert** [comment]
Yeahh.. this is an issue.

The problem is that, generally, when following links, we follow links from a resource to another resource. When we get a POST response, the body of the response is not necessarily the representation of that `startAuthResource` resource.

There's two paths to make better, and I also have a workaround:



Approach 1: The response to the `POST` response should be considered to be the _representation_ of that resource. The obvious header for this is `Content-Location`:

https://tools.ietf.org/html/rfc7231#section-3.1.4.2

If this makes the most sense for your case, we could add this feature to Ketting.

--

Approach 2: Follow links from State objects.

I had the idea to add a `.follow()` function to `State` objects. This would allow you to follow links from any body, not just things that are 'resources':

```typescript
 const startAuthResource = await apiRoot.follow("rels/authentication");
 const response = await startAuthResource.post({ data: { username } });
 const authResource = response.follow("rels/authentication/authenticate"); // <-- We're following from 'response'
```

Workaround:

```typescript
const startAuthResource = await apiRoot.follow("rels/authentication");
const response = await startAuthResource.post({ data: { username } });
const authResource = startAuthResource.go(response.links.get("rels/authentication/authenticate").href);
```

Sidenote is that it would also be nice if you could pass a `Link` type to `.go()` so that last snippet would look like:

```typescript
const startAuthResource = await apiRoot.follow("rels/authentication");
const response = await startAuthResource.post({ data: { username } });
const authResource = startAuthResource.go(response.links.get("rels/authentication/authenticate"));
```

**Comment by sazzer** [comment]
Approach 2 is what I expected to be able to do, and was surprised that it wasn't an option. That seems like the best actual solution.

The workaround you've got is almost exactly the workaround that I just came to say I've worked out too :) I didn't realise you could use `.go()` from resource objects, so my current code is making the client available to call `.go` on, which works just fine. I'm going to change it to your way though so that the actual client isn't exposed after all :)

**Comment by evert** [comment]
yeah you'll want `.go()` on the resource, because it will correctly resolve relative uris =)

**Comment by sazzer** [comment]
Seems that getting hold of the link from `response.links.get().href` has already resolved the relative URIs before I even get to that point :)

**Comment by evert** [comment]
oh! right =)

**Comment by evert** [comment]
Open a few more tickets for this. I think we'll probably have a version 7 this month. Thanks for the report!
