### ISSUE TITLE
getEmbedded() returns empty Array despite the set embedded response

### ISSUE THREAD

**Issue by mszalomski** [badgateway/ketting#407]
First of all thank you for the implementation of the ketting library - it works like a dream for most of our endpoints.

However I observed a strange behavior for one of our endpoints. The embedded GET returns an empty array, although the embedded attribute is filled in the API response.

Do you have any suggestion, how it could be fixed?

```typescript
public follow(element, ref:) {
    element.clearCache();
    return new Observable((observer) => {
      from(element.follow(ref))
        .subscribe(refData => {
          from(refData.get())
            .subscribe(data => {
              observer.next(data);
            });
        });
    });
  }

...

const projectListClient = new Client('resources/projects')
return this.follow(projectListClient, HateoasLink.SELF)
   .pipe(
     tap((data: any) => {
       this.hateoasDataRoot = data;
       if (data.getEmbedded()) {
           // .getEmbedded returns an empty array
       }
    })
   )

...
```

The response structure from the `resources/projects` endpoint looks like that:
```json
{
   "_embedded":{
      "projects":[
         {
            --- DATA FOR A SPECIFIC PROJECT ---
            "_links":{
               --- LINKS FOR A SPECIFIC PROJECT ---
            },
            "_templates":{
               --- ACTIONS FOR A SPECIFIC PROJECT ---
            }
         }
      ]
   },
   "_links":{
      "self":{
         "href":"http://localhost:4200/resources/projects"
      }
   }
}
```

1. Checked out other issues.
A specific followAll('projects') callback as suggested in https://github.com/badgateway/ketting/issues/273 and https://github.com/badgateway/ketting/issues/275 returns an empty array also.

2. Commented out element.clearCache();
Same result - empty array

**Comment by mszalomski** [comment]
Checked out other issues.
A specific followAll('projects') callback as suggested in https://github.com/badgateway/ketting/issues/275 returns an empty array also.

**Comment by lucasvog** [comment]
Same problem here.

**Comment by evert** [comment]
Hi!

`getEmbedded()` is, as you figured out not the right thing to call. There's no strong guarantees you're going to get results from it, because several mechanisms may add something new in the cache, and embedded items are not considered to be a 'true part' of the resource. They are a trick to reduce HTTP requests.

So, `followAll()` indeed is the way to go, but there's an issue. The items you embedded don't show up in the `_links` section.

Originally ketting had a feature that would automatically take any resource in `_embedded`, and automatically also turn them into a link, if items in `_embedded` were not repeated. Ketting no longer does this.

The HAL draft seems to support the idea that links shouldn't be swapped out for items in `_embedded`:

>    Servers SHOULD NOT entirely "swap out" a link for an embedded
>   resource (or vice versa) because client support for this technique is
>   OPTIONAL.

https://datatracker.ietf.org/doc/html/draft-kelly-json-hal#section-8.3

However, the original behavior existed to support people that didn't do this correctly. It appeared enough in the wild that it was worth making a workaround for. Removing this workaround was not intentional, so somewhere along the way this introduced a backwards compatibility issue. @mhum also recently ran into this.

So the quick fix is to just ensure that anything you want to follow actually appears in `_links`. I think I would like to add this behavior back though, as I think you're not going to be the last to run into this. I also think `getEmbedded()` needs a clearer warning that it's usually the wrong API =)

**Comment by mszalomski** [comment]
> So the quick fix is to just ensure that anything you want to follow actually appears in _links

Could you please provide an example, what the missing entires in _links would look like?
As you can see in the thread, there's already a self link pointing to the projects I do actually follow.

Thank you for your help

**Comment by mszalomski** [comment]
A "projects" link was inserted into the _links - Attribute. After following the given destination using the followAll function and getting the current state of the delivered resource - we still get a state with an empty embedded attribute.

API-Response
![image](https://user-images.githubusercontent.com/4322233/144216348-3591417f-1a48-4399-b4fe-ceb7d45d0c65.png)

Current state of the resource
![image](https://user-images.githubusercontent.com/4322233/144216242-47815c8c-e907-46de-bea4-90c845e3af80.png)

**Comment by evert** [comment]
@mszalomski I think that's an excellent idea. Glad you figured this out. I'm going to reopen this ticket with an updated title.

**Comment by evert** [comment]
I opened #408 and #409 to address both issues.
