### ISSUE TITLE
Using ketting with centrally-managed state libraries (in React)

### ISSUE THREAD

**Issue by dusandjovanovic** [badgateway/ketting#424]
First of all, great work on this library! 

We've stumbled upon it while looking for new ways to parse and manage json:api data more effectively. Our idea was to use **ketting** between our state-management library of choice and the back-end APIs.

Technically, these centralized state management solutions could be `Recoil`, `Redux`, etc.

However, we encountered an issue when we tried to bind our centralized state with ketting. I will leave two examples here, we used `Recoil` in both cases.

**1. First scenario, managing single resources**
```js
// Separate state
// An "atom" in Recoil terms
const [user, setUser] = useRecoilState(userAtom);

// Using ketting to fetch and parse the data
const { resourceState, resource, loading, error } = useResource<User>(USER_ENDPOINT);

useEffect(() => {
    if (!loading) {
        setUser(extractUserData(resourceState));
    }
}, [resourceState, loading, setUser]);
```

In this case, we managed to update the central state, right after the resource becomes available.

**2. Second scenario, managing collections of resources**
```js
// Separate state
// Again, an "atom"
const [userEmails, setUserEmails] = useRecoilState(userEmailsAtom);

// Using ketting for a collection of items
const { items, loading, error } = useCollection<UserEmail>(USER_EMAIL);

useEffect(() => {
    if (!loading) {
        // We can't do anything useful here
    }
}, [loading]);
```

This time, however, we were not able to properly track changes and update the state because it is out of ketting's bounds.

Your docs seem to promote another way, which is relying on `useCollection` and `useResource` hooks together. However, we cannot rely on this approach in our particular usecase. Ideally, we would like to take advantage of ketting as a mediator and form our state structure separately. And that doesn't quite work when using `useCollection`.

Are you possibly working on a something that could provide APIs we need in the future?

Are we missing something? If so, tell us so that we could take advantage of your library in a better way.

**Comment by evert** [comment]
Hi @dusandjovanovic !

I think the way most of of the applications are currently built using these hooks, is by using Ketting itself as a state management library. Ketting has a local cache, and if there are several `useResource` hooks pointing to the same resource, they will also point to the same data, and updates to resource state gets automatically propagated via events.

This works particularly well for cases where every entity has a true address, which I believe is a bit harder with JSON:API, because the last time I checked, there's no way to read a collection with JSON:API that lets us 'guess' the full representation of the members  of the collection (compared to something like HAL, where we assume 'embedded' resources are *exact* representations, letting us build the cache for every member of a collection).

When using something like Recoil, (correct me if I'm wrong), I assume that you would want the source of truth and all state to come from Recoil, and I feel this is a bit in conflict with the Ketting hooks. If this is the path you're taking, looking at the Recoil documentation I think that the right integration point (for fetching data) might be to write a 'selector':

https://recoiljs.org/docs/guides/asynchronous-data-queries#asynchronous-example

I know very little about recoil, so I'm not sure if this is right... but I do believe that if you use Recoil for generally managing all state, then the integration point with Ketting is the way Recoil wants to deal with data, and not via the hooks.

One thing I can also recommend is look at how people integrate GraphQL/Apollo with Recoil. Apollo has a similar hook (useQuery) that also returns `loading, data, error`, but I would assume that Recoil users that integrate GraphQL also find a way to integrate data fetching in Recoil and not use the Apollo hooks directly.

I would be very curious how this final solution looks like though, and I'm also happy to jump on a chat to go through this more. If I can help you get this to work elegantly, and we end up with a Recoil page in the wiki I think that would be a win:win.

If you want a more direct line of communication, I can be reached via matrix: [@evert:badgateway.net](https://matrix.to/#/@evert:badgateway.net)

**Comment by evert** [comment]
Sorry for a bit of a slow response here.

If you can figure out how to populate a cache for each single item, if we have a collection of items this is solvable. This is difficult for me as the author of this lib, because I'm a very casual user of JSON:API, so I worry that I will not be able to come up with a solution that will make sense for real-world applications.

This is partially why the HAL bits are currently getting the most love; I use that format every day.

So what this needs is really a champion and a new contributor. Alternatively you could hire me through my company <badgateway.net>, but otherwise until I have a need for this myself I don't really see this happening yet unfortunately =(
